const OWNER='sivakalyankaricheti',REPO='Kalyan-Web',BRANCH='main',DATA_PATH='portfolio-data.json',API='https://api.github.com';
let portfolioData=null;
const $=id=>document.getElementById(id);
const encodeBase64=text=>{const bytes=new TextEncoder().encode(text);let binary='';bytes.forEach(byte=>binary+=String.fromCharCode(byte));return btoa(binary)};
const decodeBase64=value=>new TextDecoder().decode(Uint8Array.from(atob(value.replace(/\n/g,'')),c=>c.charCodeAt(0)));

async function loadData(){const response=await fetch(`${DATA_PATH}?v=${Date.now()}`,{cache:'no-store'});portfolioData=await response.json();fillForm(portfolioData)}
function fillForm(data){$('name').value=data.name;$('location').value=data.location;$('headline').value=data.headline;$('about-primary').value=data.aboutPrimary;$('about-secondary').value=data.aboutSecondary;$('email').value=data.contact.email;$('phone').value=data.contact.phone;$('linkedin').value=data.contact.linkedin;$('achievement-editor').replaceChildren();data.achievements.forEach(addAchievement);$('certificate-editor').replaceChildren();data.certificates.forEach(addCertificate)}
function addAchievement(value={year:'',title:'',description:''}){const row=$('achievement-template').content.firstElementChild.cloneNode(true);Object.entries(value).forEach(([key,val])=>{const field=row.querySelector(`[data-key="${key}"]`);if(field)field.value=val});wireRemove(row);$('achievement-editor').append(row)}
function addCertificate(value={name:'',issuer:''}){const row=$('certificate-template').content.firstElementChild.cloneNode(true);Object.entries(value).forEach(([key,val])=>row.querySelector(`[data-key="${key}"]`).value=val);wireRemove(row);$('certificate-editor').append(row)}
function wireRemove(row){row.querySelector('.remove').addEventListener('click',()=>row.remove())}
document.querySelectorAll('[data-add]').forEach(button=>button.addEventListener('click',()=>button.dataset.add==='achievement'?addAchievement():addCertificate()));
function rows(selector){return [...document.querySelectorAll(selector)].map(row=>Object.fromEntries([...row.querySelectorAll('[data-key]')].map(field=>[field.dataset.key,field.value.trim()])))}
function collectData(){return {...portfolioData,name:$('name').value.trim(),location:$('location').value.trim(),headline:$('headline').value.trim(),aboutPrimary:$('about-primary').value.trim(),aboutSecondary:$('about-secondary').value.trim(),contact:{email:$('email').value.trim(),phone:$('phone').value.trim(),linkedin:$('linkedin').value.trim()},achievements:rows('.achievement-row'),certificates:rows('.certificate-row')}}
async function github(path,token,options={}){const response=await fetch(`${API}/repos/${OWNER}/${REPO}/contents/${path}`,{...options,headers:{Accept:'application/vnd.github+json',Authorization:`Bearer ${token}`,'X-GitHub-Api-Version':'2022-11-28',...(options.headers||{})}});if(!response.ok){const body=await response.json().catch(()=>({}));throw new Error(body.message||`GitHub returned ${response.status}`)}return response.json()}
async function uploadImage(file,token){if(!file)return portfolioData.profileImage; if(file.size>2*1024*1024)throw new Error('Profile image must be smaller than 2 MB');const ext=file.type==='image/png'?'png':file.type==='image/webp'?'webp':'jpg';const path=`assets/profile.${ext}`;let sha;try{sha=(await github(path,token)).sha}catch(error){if(!error.message.includes('Not Found'))throw error}const bytes=new Uint8Array(await file.arrayBuffer());let binary='';bytes.forEach(byte=>binary+=String.fromCharCode(byte));await github(path,token,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:'Update portfolio profile image',content:btoa(binary),branch:BRANCH,...(sha?{sha}:{})})});return `${path}?v=${Date.now()}`}
$('editor-form').addEventListener('submit',async event=>{event.preventDefault();const button=document.querySelector('.publish-button'),message=$('publish-message'),token=$('github-token').value.trim();if(!token){message.className='error';message.textContent='Enter a GitHub access token to publish.';return}button.disabled=true;message.className='';message.textContent='Publishing changes…';try{const current=await github(DATA_PATH,token);const next=collectData();next.profileImage=await uploadImage($('profile-upload').files[0],token);await github(DATA_PATH,token,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:'Update portfolio content',content:encodeBase64(`${JSON.stringify(next,null,2)}\n`),sha:current.sha,branch:BRANCH})});portfolioData=next;$('github-token').value='';$('status').textContent='Published';message.className='success';message.innerHTML='Published successfully. GitHub Pages will refresh in about one minute. <a href="index.html">View the portfolio →</a>'}catch(error){message.className='error';message.textContent=`Could not publish: ${error.message}`}finally{button.disabled=false}});
loadData().catch(error=>{$('publish-message').className='error';$('publish-message').textContent=`Could not load portfolio data: ${error.message}`});
