const OWNER='sivakalyankaricheti',REPO='Kalyan-Web',BRANCH='main',DATA_PATH='portfolio-data.json',API='https://api.github.com';
const PASSWORD_HASH='790ec123f0e942a59ff130a63f4759f2b76e51145cfe59d6b9d5b091b7889335';
let portfolioData=null;
const $=id=>document.getElementById(id);
const encodeBase64=text=>{const bytes=new TextEncoder().encode(text);let binary='';bytes.forEach(byte=>binary+=String.fromCharCode(byte));return btoa(binary)};
const sha256=async value=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value)))).map(byte=>byte.toString(16).padStart(2,'0')).join('');
async function github(path,token,options={}){const response=await fetch(`${API}/repos/${OWNER}/${REPO}/contents/${path}`,{...options,headers:{Accept:'application/vnd.github+json',Authorization:`Bearer ${token}`,'X-GitHub-Api-Version':'2022-11-28',...(options.headers||{})}});if(!response.ok){const body=await response.json().catch(()=>({}));throw new Error(body.message||`GitHub returned ${response.status}`)}return response.json()}
async function loadData(){const response=await fetch(`${DATA_PATH}?v=${Date.now()}`,{cache:'no-store'});if(!response.ok)throw new Error('Portfolio data unavailable');portfolioData=await response.json();fillForm(portfolioData)}
function clearAndFill(id,items=[],builder){$(id).replaceChildren();(items||[]).forEach(builder)}
function addFromTemplate(templateId,targetId,value){const row=$(templateId).content.firstElementChild.cloneNode(true);Object.entries(value).forEach(([key,val])=>{const field=row.querySelector(`[data-key="${key}"]`);if(field)field.value=val||''});row.querySelector('.remove').addEventListener('click',()=>row.remove());$(targetId).append(row)}
const addPersonalInfo=(value={label:'Custom detail',value:''})=>addFromTemplate('personal-info-template','personal-info-editor',value);
const addPersonal=(value={value:'',label:''})=>addFromTemplate('personal-template','personal-editor',value);
const addSocial=(value={label:'',url:''})=>addFromTemplate('social-template','social-editor',value);
const addExperience=(value={period:'',location:'',title:'',organization:'',description:''})=>addFromTemplate('experience-template','experience-editor',value);
const addProject=(value={number:'',category:'',title:'',description:'',link:''})=>addFromTemplate('project-template','project-editor',value);
const addGallery=(value={title:'',description:'',image:'',url:''})=>addFromTemplate('gallery-template','gallery-editor',value);
const addSkill=(value={value:''})=>addFromTemplate('skill-template','skill-editor',value);
const addAchievement=(value={year:'',title:'',description:''})=>addFromTemplate('achievement-template','achievement-editor',value);
const addCertificate=(value={name:'',issuer:'',url:''})=>addFromTemplate('certificate-template','certificate-editor',value);
function fillForm(data){$('name').value=data.name;$('location').value=data.location;$('headline').value=data.headline;$('about-primary').value=data.aboutPrimary;$('about-secondary').value=data.aboutSecondary;$('email').value=data.contact.email;$('phone').value=data.contact.phone;clearAndFill('personal-info-editor',data.personalInfo,addPersonalInfo);clearAndFill('personal-editor',data.personalDetails,addPersonal);clearAndFill('social-editor',data.socialLinks,addSocial);clearAndFill('experience-editor',data.experience,addExperience);clearAndFill('project-editor',data.projects,addProject);clearAndFill('gallery-editor',data.gallery,addGallery);clearAndFill('skill-editor',(data.skills||[]).map(value=>({value})),addSkill);clearAndFill('achievement-editor',data.achievements,addAchievement);clearAndFill('certificate-editor',data.certificates,addCertificate)}
const addActions={personal:addPersonal,social:addSocial,experience:addExperience,project:addProject,gallery:addGallery,skill:addSkill,achievement:addAchievement,certificate:addCertificate};
document.addEventListener('click',event=>{const addButton=event.target.closest('[data-add]');if(addButton){event.preventDefault();addActions[addButton.dataset.add]?.();return}if(event.target.closest('#add-personal-info')){event.preventDefault();addPersonalInfo({label:$('personal-info-menu').value,value:''})}});
function rows(selector){return [...document.querySelectorAll(selector)].map(row=>Object.fromEntries([...row.querySelectorAll('[data-key]')].map(field=>[field.dataset.key,field.value.trim()]))) }
function collectData(){return {...portfolioData,name:$('name').value.trim(),location:$('location').value.trim(),headline:$('headline').value.trim(),aboutPrimary:$('about-primary').value.trim(),aboutSecondary:$('about-secondary').value.trim(),contact:{email:$('email').value.trim(),phone:$('phone').value.trim()},personalInfo:rows('.personal-info-row'),personalDetails:rows('.personal-row'),socialLinks:rows('.social-row'),experience:rows('.experience-row'),projects:rows('.project-row'),gallery:rows('.gallery-row'),skills:rows('.skill-row').map(item=>item.value).filter(Boolean),achievements:rows('.achievement-row'),certificates:rows('.certificate-row')}}
const safeFilename=name=>name.toLowerCase().replace(/[^a-z0-9.]+/g,'-').replace(/^-|-$/g,'');
async function uploadAsset(file,folder,token){if(file.size>5*1024*1024)throw new Error(`${file.name} is larger than 5 MB`);const path=`assets/${folder}/${Date.now()}-${safeFilename(file.name)}`;const bytes=new Uint8Array(await file.arrayBuffer());let binary='';bytes.forEach(byte=>binary+=String.fromCharCode(byte));await github(path,token,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:`Upload ${folder} asset`,content:btoa(binary),branch:BRANCH})});return `${path}?v=${Date.now()}`}
async function uploadImage(file,token){if(!file)return portfolioData.profileImage;if(file.size>2*1024*1024)throw new Error('Profile image must be smaller than 2 MB');return uploadAsset(file,'profile',token)}
async function uploadManagedAssets(next,token){const certificateRows=[...document.querySelectorAll('.certificate-row')];for(let i=0;i<certificateRows.length;i++){const file=certificateRows[i].querySelector('.certificate-file').files[0];if(file)next.certificates[i].url=await uploadAsset(file,'certificates',token)}const galleryRows=[...document.querySelectorAll('.gallery-row')];for(let i=0;i<galleryRows.length;i++){const file=galleryRows[i].querySelector('.gallery-file').files[0];if(file)next.gallery[i].image=await uploadAsset(file,'gallery',token);if(!next.gallery[i].image)throw new Error(`Add an image for gallery item ${i+1}`)}return next}
$('login-form').addEventListener('submit',async event=>{event.preventDefault();const input=$('admin-password'),message=$('login-message'),button=event.submitter;button.disabled=true;message.className='';message.textContent='Checking password...';try{if(await sha256(input.value)!==PASSWORD_HASH)throw new Error('Invalid password');input.value='';await loadData();document.body.classList.remove('locked');message.textContent=''}catch(error){message.className='error';message.textContent=error.message==='Invalid password'?'Incorrect password. Please try again.':`Could not load editor: ${error.message}`}finally{button.disabled=false}});
$('logout').addEventListener('click',()=>{portfolioData=null;$('github-token').value='';document.body.classList.add('locked');$('status').textContent='Draft mode';$('publish-message').textContent=''});
$('editor-form').addEventListener('submit',async event=>{event.preventDefault();const button=document.querySelector('.publish-button'),message=$('publish-message'),token=$('github-token').value.trim();if(!token){message.className='error';message.textContent='Enter your GitHub access token to publish.';return}button.disabled=true;message.className='';message.textContent='Uploading files and publishing changes...';try{const current=await github(DATA_PATH,token);let next=collectData();next.profileImage=await uploadImage($('profile-upload').files[0],token);next=await uploadManagedAssets(next,token);await github(DATA_PATH,token,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:'Update portfolio content',content:encodeBase64(`${JSON.stringify(next,null,2)}\n`),sha:current.sha,branch:BRANCH})});portfolioData=next;$('github-token').value='';$('status').textContent='Published';message.className='success';message.innerHTML='Published successfully. GitHub Pages will refresh in about one minute. <a href="index.html">View the portfolio</a>'}catch(error){message.className='error';message.textContent=`Could not publish: ${error.message}`}finally{button.disabled=false}});
