const menuButton=document.querySelector('.menu-button');
const navLinks=document.querySelector('.nav-links');
menuButton.addEventListener('click',()=>{const open=menuButton.getAttribute('aria-expanded')==='true';menuButton.setAttribute('aria-expanded',String(!open));navLinks.classList.toggle('open')});
navLinks.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{navLinks.classList.remove('open');menuButton.setAttribute('aria-expanded','false')}));
document.getElementById('year').textContent=new Date().getFullYear();
document.getElementById('skill-detail-close').addEventListener('click',()=>{document.getElementById('skill-detail').hidden=true;document.querySelectorAll('.skill-chip').forEach(node=>{node.classList.remove('active');node.setAttribute('aria-pressed','false')})});

const safeText=(value='')=>String(value);
async function loadPortfolio(){
  try{
    const response=await fetch(`portfolio-data.json?v=${Date.now()}`,{cache:'no-store'});
    if(!response.ok)throw new Error('Portfolio data unavailable');
    const data=await response.json();
    const names=data.name.trim().split(/\s+/); const last=names.pop()||'';
    document.getElementById('hero-first-name').textContent=names.join(' ')||last;
    document.getElementById('hero-last-name').textContent=names.length?`${last}.`:'';
    document.getElementById('hero-title').textContent=safeText(data.headline);
    document.querySelector('.eyebrow').textContent=`${safeText(data.location)} · Open to opportunities`;
    document.getElementById('about-primary').textContent=safeText(data.aboutPrimary);
    document.getElementById('about-secondary').textContent=safeText(data.aboutSecondary);
    const image=document.getElementById('profile-image'); image.src=data.profileImage||'assets/profile.jpg'; image.alt=`Portrait of ${data.name}`;
    const email=document.getElementById('email-link'); email.href=`mailto:${data.contact.email}`; email.textContent=`${data.contact.email} ↗`;
    const phone=document.getElementById('phone-link'); phone.href=`tel:${data.contact.phone.replace(/\s/g,'')}`; phone.textContent=`${data.contact.phone} ↗`;
    const contactLinks=document.getElementById('contact-links');
    const socialNodes=(data.socialLinks||[]).map(item=>{const link=document.createElement('a');link.href=item.url;link.target='_blank';link.rel='noopener noreferrer';link.textContent=`${item.label} ↗`;return link});
    contactLinks.replaceChildren(email,phone,...socialNodes);
    document.getElementById('personal-info-list').replaceChildren(...(data.personalInfo||[]).filter(item=>item.value).map(item=>{const row=document.createElement('div');row.className='personal-info-item';const label=document.createElement('span');label.textContent=item.label;const value=document.createElement('strong');value.textContent=item.value;row.append(label,value);return row}));
    document.getElementById('personal-details').replaceChildren(...(data.personalDetails||[]).map(item=>{const box=document.createElement('div');const value=document.createElement('strong');value.textContent=item.value;const label=document.createElement('span');label.textContent=item.label;box.append(value,label);return box}));
    const skillCloud=document.getElementById('skill-cloud'),skillDetail=document.getElementById('skill-detail'),skillTitle=document.getElementById('skill-detail-title'),skillDescription=document.getElementById('skill-detail-description');
    const skills=(data.skills||[]).map(value=>typeof value==='string'?{name:value,description:''}:value);
    skillCloud.replaceChildren(...skills.map(item=>{const skill=document.createElement('button');skill.type='button';skill.className='skill-chip';skill.textContent=item.name||item.value||'';skill.addEventListener('click',()=>{skillCloud.querySelectorAll('.skill-chip').forEach(node=>{node.classList.remove('active');node.setAttribute('aria-pressed','false')});skill.classList.add('active');skill.setAttribute('aria-pressed','true');skillTitle.textContent=item.name||item.value||'';skillDescription.textContent=item.description||'Details for this skill can be added from the Admin page.';skillDetail.hidden=false;skillDetail.scrollIntoView({behavior:'smooth',block:'nearest'})});skill.setAttribute('aria-pressed','false');return skill}));
    document.getElementById('experience-list').replaceChildren(...(data.experience||[]).map(item=>{const article=document.createElement('article');article.className='timeline-item reveal';const meta=document.createElement('div');const period=document.createElement('span');period.textContent=item.period;const location=document.createElement('span');location.textContent=item.location;meta.append(period,location);const content=document.createElement('div');const title=document.createElement('h3');title.textContent=item.title;const organization=document.createElement('p');organization.className='muted';organization.textContent=item.organization;const description=document.createElement('p');description.textContent=item.description;content.append(title,organization,description);article.append(meta,content);return article}));
    document.getElementById('project-list').replaceChildren(...(data.projects||[]).map((item,index)=>{const article=document.createElement('article');article.className=`project reveal${index===0?' project-featured':''}`;const number=document.createElement('div');number.className='project-number';number.textContent=item.number;const content=document.createElement('div');const category=document.createElement('p');category.className='tag';category.textContent=item.category;const title=document.createElement('h3');title.textContent=item.title;const description=document.createElement('p');description.textContent=item.description;content.append(category,title,description);const links=document.createElement('div');links.className='project-links';const candidates=[{label:item.link1Label||'View project',url:item.link1||item.link},{label:item.link2Label||'More details',url:item.link2}];candidates.filter(entry=>entry.url).forEach(entry=>{const link=document.createElement('a');link.className='project-link';link.href=entry.url;link.target='_blank';link.rel='noopener noreferrer';link.textContent=`${entry.label} ↗`;links.append(link)});if(links.childElementCount)content.append(links);article.append(number,content);return article}));
    const galleryItems=data.gallery||[];document.getElementById('gallery-empty').hidden=galleryItems.length>0;document.getElementById('gallery-grid').replaceChildren(...galleryItems.map(item=>{const card=document.createElement('article');card.className='gallery-card reveal';const image=document.createElement('img');image.src=item.image;image.alt=item.title;image.loading='lazy';const body=document.createElement('div');const title=document.createElement('h3');title.textContent=item.title;const description=document.createElement('p');description.textContent=item.description||'';body.append(title,description);if(item.url){const link=document.createElement('a');link.href=item.url;link.target='_blank';link.rel='noopener noreferrer';link.textContent='Open link ↗';body.append(link)}card.append(image,body);return card}));
    document.getElementById('achievement-grid').replaceChildren(...data.achievements.map(item=>{const card=document.createElement('article');card.className='achievement-card reveal';const year=document.createElement('span');year.className='year';year.textContent=item.year;const title=document.createElement('h3');title.textContent=item.title;const description=document.createElement('p');description.textContent=item.description;card.append(year,title,description);return card}));
    document.getElementById('certificate-list').replaceChildren(...data.certificates.map(item=>{const row=document.createElement(item.url?'a':'div');row.className='certificate-item';if(item.url){row.href=item.url;row.target='_blank';row.rel='noopener noreferrer'}const content=document.createElement('div');const name=document.createElement('strong');name.textContent=item.name;const issuer=document.createElement('span');issuer.textContent=item.issuer;content.append(name,issuer);row.append(content);if(item.url){const preview=document.createElement('span');preview.className='certificate-action';preview.textContent='View certificate ↗';row.append(preview)}return row}));
    observeReveals();
  }catch(error){console.error(error)}
}
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.12});
function observeReveals(){document.querySelectorAll('.reveal:not(.visible)').forEach(el=>observer.observe(el))}
observeReveals();loadPortfolio();
